# -*- coding: utf-8 -*-
"""Untitled44.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/113GAwF6tC6YkTZ0H-DowJyVZC2sNN2-s
"""

import numpy as np
import pandas as pd

# Load the training data
DataX = pd.read_csv("DataX.csv")  # Replace with the actual path to your input data file
DataY = pd.read_csv("DataY.csv")  # Replace with the actual path to your output data file

# Add a bias term (intercept) to the input features
DataX.insert(0, "Bias", 1)

# Convert data to NumPy arrays
X = DataX.to_numpy()
y = DataY.to_numpy()

# Calculate the parameters (theta) using the closed-form solution
theta = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)

# Print the learned parameters (theta)
print("Learned Parameters (theta):")
print(theta)