# -*- coding: utf-8 -*-
"""Untitled44.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/113GAwF6tC6YkTZ0H-DowJyVZC2sNN2-s
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Load the input data and labels
DataX = pd.read_csv("DataX.csv")  # Replace with the actual path to your data file
ClassY = pd.read_csv("ClassY.csv")  # Replace with the actual path to your class labels file

# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, Y_train, Y_test = train_test_split(DataX, ClassY, test_size=0.2, random_state=42)

# Initialize and train the logistic regression model
model = LogisticRegression()
model.fit(X_train, Y_train)

# Make predictions on the test set
Y_pred = model.predict(X_test)

# Evaluate the model
CheckAccuracy = accuracy_score(Y_test, Y_pred)
print(f"Accuracy: {CheckAccuracy * 100:.2f}%")

# Print classification report for detailed metrics
classReport = classification_report(Y_test, Y_pred)
print("\nClassification Report:")
print(classReport)